server:
  port: 10101


spring:
  application:
    name: think-cloud-quickstart-apiserver
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: QS
          uri: lb://think-cloud-quickstart-ctl
          predicates:
            - Path=/qs/**
          filters:
            - StripPrefix=1


















